config/routes.rb
Rails.application.routes.draw do
  get "/" => "homes#top"
  root :to => 'books#top'
  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   validates :title, presence: true
  validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
   validates :Title, presence: true
  validates :Body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
     @book = Book.new
  end

  def create

    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), flash: { notice: 'Book was successfully created.' }
    else
       @books = Book.all
      render :index
    end

  end

  def index
    @book = Book.new
     @books = Book.all
  end

  def show
     @book = Book.find(params[:id])
  end

  def edit
     @book = Book.find(params[:id])
  end

  def update
    @book = Book.new(book_params)
    book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(book.id), flash: { notice: 'Book was successfully update.' }
     else
       @books = Book.all
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to book
  end

  private

 def book_params
    params.require(:book).permit(:title, :body)
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing</h1>
 <%= form_with model: @book do |f| %>
 <p>Title</p>
 <td><%= f.text_field :title %></td>
 <p>Body</p>
 <td><%= f.text_field :body %></td>
<p>
<%= f.submit 'Update Book' %>
</p>
 <% end %>
  <p>
  <td> <%= link_to 'Show', book_path(@book.id) %></td>
  <a class="back" href="/books">Back</a> 
  </p>

app/views/books/index.html.erb
    <p id="notice"></p>

</div>
<h1>Books</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

  <% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td> <%= link_to 'Show', book_path(book.id) %></td>
    <td> <%= link_to 'Edit', edit_book_path(book.id) %></td>
    <td> <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  
  </tr>
  <% end %>



  </tbody>
</table>
<h2>New book</h2>
<%= form_with model: @book ,url: books_path, method: :post do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
 <% if flash[:notice] %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>
 <p>
 <strong>Title:</strong>
 <td><%= @book.title %></td>
 </p>

<p>
<strong>Body:</strong>
 <td><%= @book.body %></td>
</p>
<p>
   <td> <%= link_to 'Edit', edit_book_path(@book.id) %></td>
   <a class="back" href="/books">Back</a> 
</p>

app/views/homes/top.html.erb
<body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p> <a href="/books">start</a></p>    	
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>